//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHash
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string mail { get; set; }
        public string friendList { get; set; }
        public string sypherPriv { get; set; }
        public string sypherPub { get; set; }
        public string password { get; set; }
    }
}
